# Generated by Django 2.0.6 on 2018-07-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyware', '0003_auto_20180710_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, help_text='Currency symbol', max_length=10, null=True, verbose_name='Symbol'),
        ),
    ]
